name: Check arduino

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1

  build:
    name: Test compiling examples for UNO
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v3
